[package]
name = "multi"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
tokio = { version = "1.44", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = "0.26"
tungstenite = "0.26"
